[
  {
    "transactionId": "TXN-1001",
    "dateTime": "2026-09-17T08:15:00Z",
    "customerId": "CUST-9921",
    "productId": "PROD-5501",
    "productUnitCostPrice": 45.00,
    "productUnitSellingPrice": 75.00,
    "productQuantity": 10,
    "paymentStatus": "Paid",
    "productReturnStatus": "No",
    "operatingExpenses": 45.00,
    "deliveryEmployeeId": "EMP-0412",
    "deliveryLocation": "Jubilee Mall, KNUST Commercial Area",
    "deliveryDistance": 1.2,
    "deliveryTripDuration": 8,
    "deliveryRating": 5
  },
  {
    "transactionId": "TXN-1002",
    "dateTime": "2026-09-17T09:00:00Z",
    "customerId": "CUST-4412",
    "productId": "PROD-5501",
    "productUnitCostPrice": 45.00,
    "productUnitSellingPrice": 75.00,
    "productQuantity": 2,
    "paymentStatus": "Unpaid",
    "productReturnStatus": "No",
    "operatingExpenses": 15.00,
    "deliveryEmployeeId": "EMP-0412",
    "deliveryLocation": "Brunei Complex, KNUST Campus",
    "deliveryDistance": 2.5,
    "deliveryTripDuration": 25,
    "deliveryRating": 2
  },
  {
    "transactionId": "TXN-1003",
    "dateTime": "2026-09-17T10:30:00Z",
    "customerId": "CUST-1105",
    "productId": "PROD-8822",
    "productUnitCostPrice": 12.00,
    "productUnitSellingPrice": 25.00,
    "productQuantity": 100,
    "paymentStatus": "Paid",
    "productReturnStatus": "No",
    "operatingExpenses": 180.00,
    "deliveryEmployeeId": "EMP-0988",
    "deliveryLocation": "Unity Hall (Conti), KNUST",
    "deliveryDistance": 1.8,
    "deliveryTripDuration": 12,
    "deliveryRating": 4
  },
  {
    "transactionId": "TXN-1004",
    "dateTime": "2026-09-17T11:15:00Z",
    "customerId": "CUST-8831",
    "productId": "PROD-1092",
    "productUnitCostPrice": 110.00,
    "productUnitSellingPrice": 195.00,
    "productQuantity": 5,
    "paymentStatus": "Paid",
    "productReturnStatus": "Yes",
    "operatingExpenses": 65.00,
    "deliveryEmployeeId": "EMP-0412",
    "deliveryLocation": "Ayeduase Gate, Kumasi",
    "deliveryDistance": 3.2,
    "deliveryTripDuration": 18,
    "deliveryRating": 3
  },
  {
    "transactionId": "TXN-1005",
    "dateTime": "2026-09-17T13:00:00Z",
    "customerId": "CUST-3310",
    "productId": "PROD-5501",
    "productUnitCostPrice": 45.00,
    "productUnitSellingPrice": 75.00,
    "productQuantity": 40,
    "paymentStatus": "Paid",
    "productReturnStatus": "No",
    "operatingExpenses": 110.00,
    "deliveryEmployeeId": "EMP-0754",
    "deliveryLocation": "SRC Hostel, KNUST Campus",
    "deliveryDistance": 2.1,
    "deliveryTripDuration": 10,
    "deliveryRating": 5
  },
  {
    "transactionId": "TXN-1006",
    "dateTime": "2026-09-17T14:45:00Z",
    "customerId": "CUST-4412",
    "productId": "PROD-3304",
    "productUnitCostPrice": 6.50,
    "productUnitSellingPrice": 15.00,
    "productQuantity": 250,
    "paymentStatus": "Unpaid",
    "productReturnStatus": "No",
    "operatingExpenses": 210.00,
    "deliveryEmployeeId": "EMP-0988",
    "deliveryLocation": "Brunei Complex, KNUST Campus",
    "deliveryDistance": 2.5,
    "deliveryTripDuration": 15,
    "deliveryRating": 4
  },
  {
    "transactionId": "TXN-1007",
    "dateTime": "2026-09-18T08:00:00Z",
    "customerId": "CUST-9921",
    "productId": "PROD-8822",
    "productUnitCostPrice": 12.00,
    "productUnitSellingPrice": 25.00,
    "productQuantity": 15,
    "paymentStatus": "Paid",
    "productReturnStatus": "No",
    "operatingExpenses": 30.00,
    "deliveryEmployeeId": "EMP-0412",
    "deliveryLocation": "Jubilee Mall, KNUST Commercial Area",
    "deliveryDistance": 1.2,
    "deliveryTripDuration": 7,
    "deliveryRating": 5
  },
  {
    "transactionId": "TXN-1008",
    "dateTime": "2026-09-18T09:30:00Z",
    "customerId": "CUST-2254",
    "productId": "PROD-1092",
    "productUnitCostPrice": 110.00,
    "productUnitSellingPrice": 195.00,
    "productQuantity": 20,
    "paymentStatus": "Paid",
    "productReturnStatus": "No",
    "operatingExpenses": 150.00,
    "deliveryEmployeeId": "EMP-0754",
    "deliveryLocation": "Kotei, Kumasi",
    "deliveryDistance": 4.5,
    "deliveryTripDuration": 22,
    "deliveryRating": 4
  },
  {
    "transactionId": "TXN-1009",
    "dateTime": "2026-09-18T11:00:00Z",
    "customerId": "CUST-7741",
    "productId": "PROD-2210",
    "productUnitCostPrice": 85.00,
    "productUnitSellingPrice": 140.00,
    "productQuantity": 8,
    "paymentStatus": "Unpaid",
    "productReturnStatus": "No",
    "operatingExpenses": 70.00,
    "deliveryEmployeeId": "EMP-0988",
    "deliveryLocation": "Bomso, Kumasi",
    "deliveryDistance": 3.8,
    "deliveryTripDuration": 26,
    "deliveryRating": 4
  },
  {
    "transactionId": "TXN-1010",
    "dateTime": "2026-09-18T13:15:00Z",
    "customerId": "CUST-1105",
    "productId": "PROD-5501",
    "productUnitCostPrice": 45.00,
    "productUnitSellingPrice": 75.00,
    "productQuantity": 50,
    "paymentStatus": "Paid",
    "productReturnStatus": "No",
    "operatingExpenses": 140.00,
    "deliveryEmployeeId": "EMP-0754",
    "deliveryLocation": "Unity Hall (Conti), KNUST",
    "deliveryDistance": 1.8,
    "deliveryTripDuration": 11,
    "deliveryRating": 5
  },
  {
    "transactionId": "TXN-1011",
    "dateTime": "2026-09-19T09:00:00Z",
    "customerId": "CUST-5562",
    "productId": "PROD-3304",
    "productUnitCostPrice": 6.50,
    "productUnitSellingPrice": 15.00,
    "productQuantity": 500,
    "paymentStatus": "Paid",
    "productReturnStatus": "No",
    "operatingExpenses": 320.00,
    "deliveryEmployeeId": "EMP-0988",
    "deliveryLocation": "Kentinkrono, Kumasi",
    "deliveryDistance": 5.5,
    "deliveryTripDuration": 30,
    "deliveryRating": 4
  },
  {
    "transactionId": "TXN-1012",
    "dateTime": "2026-09-19T10:45:00Z",
    "customerId": "CUST-8831",
    "productId": "PROD-2210",
    "productUnitCostPrice": 85.00,
    "productUnitSellingPrice": 140.00,
    "productQuantity": 2,
    "paymentStatus": "Paid",
    "productReturnStatus": "No",
    "operatingExpenses": 40.00,
    "deliveryEmployeeId": "EMP-0412",
    "deliveryLocation": "Ayeduase Gate, Kumasi",
    "deliveryDistance": 3.2,
    "deliveryTripDuration": 15,
    "deliveryRating": 5
  },
  {
    "transactionId": "TXN-1013",
    "dateTime": "2026-09-19T12:00:00Z",
    "customerId": "CUST-6619",
    "productId": "PROD-9900",
    "productUnitCostPrice": 210.00,
    "productUnitSellingPrice": 350.00,
    "productQuantity": 1,
    "paymentStatus": "Unpaid",
    "productReturnStatus": "No",
    "operatingExpenses": 55.00,
    "deliveryEmployeeId": "EMP-0754",
    "deliveryLocation": "University Hall (Katanga), KNUST",
    "deliveryDistance": 1.5,
    "deliveryTripDuration": 10,
    "deliveryRating": 3
  },
  {
    "transactionId": "TXN-1014",
    "dateTime": "2026-09-19T14:00:00Z",
    "customerId": "CUST-4412",
    "productId": "PROD-8822",
    "productUnitCostPrice": 12.00,
    "productUnitSellingPrice": 25.00,
    "productQuantity": 12,
    "paymentStatus": "Paid",
    "productReturnStatus": "No",
    "operatingExpenses": 25.00,
    "deliveryEmployeeId": "EMP-0412",
    "deliveryLocation": "Brunei Complex, KNUST Campus",
    "deliveryDistance": 2.5,
    "deliveryTripDuration": 14,
    "deliveryRating": 5
  },
  {
    "transactionId": "TXN-1015",
    "dateTime": "2026-09-19T15:30:00Z",
    "customerId": "CUST-3310",
    "productId": "PROD-1092",
    "productUnitCostPrice": 110.00,
    "productUnitSellingPrice": 195.00,
    "productQuantity": 15,
    "paymentStatus": "Paid",
    "productReturnStatus": "No",
    "operatingExpenses": 115.00,
    "deliveryEmployeeId": "EMP-0754",
    "deliveryLocation": "SRC Hostel, KNUST Campus",
    "deliveryDistance": 2.1,
    "deliveryTripDuration": 12,
    "deliveryRating": 4
  }
]
